version: '3.8' # Docker Compose versiyonunu güncelleyin (obsolete uyarısı giderilir)

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:notificationdb;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
